### ISSUE TITLE
readme勘误

### ISSUE THREAD

**Issue by Gnomeek** [leadream/juuun.io#4]
1. yarn develop 应为 yarn run dev
2. mac下需要手动brew install libpng包，否则无法正常编译
3. 文件树里没找到deploy.sh

**Comment by leadream** [comment]
@Gnomeek 谢谢，1、3 我忘记更新了，晚点改一下。

**Comment by leadream** [comment]
@Gnomeek 现在是通过 `.github/workflows` 下的 GitHub Action 文件部署的。
